# Generated by Django 4.1.7 on 2023-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_gender_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='materials_provide',
            field=models.ManyToManyField(blank=True, to='school_app.material'),
        ),
    ]
