# Generated by Django 4.1.7 on 2023-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_student_materials_provide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='materials_provide',
            field=models.ManyToManyField(to='school_app.material'),
        ),
    ]
